/* Indian Stock Pro — TRIAL Compare UI */
(function(){
  "use strict";
  var selected=[],data={universe:[],research:{},quotes:{},fund:{}},ready=false,loading=null,live={};
  var PROXIES=["https://corsproxy.io/?url=","https://api.allorigins.win/raw?url="];
  function norm(v){return String(v||"").trim().toUpperCase()}
  function esc(v){return String(v==null?"":v).replace(/[&<>"']/g,function(m){return{"&":"&amp;","<":"&lt;",">":"&gt;",'"':'&quot;',"'":"&#039;"}[m]})}
  function num(v){var n=Number(v);return Number.isFinite(n)?n:null}
  function money(v){var n=num(v);return n==null?"—":"₹"+n.toLocaleString("en-IN",{minimumFractionDigits:2,maximumFractionDigits:2})}
  function score(v){var n=num(v);return n==null?"—":n.toFixed(1)+"/100"}
  function save(){sessionStorage.setItem("isp_compare",JSON.stringify(selected.slice(0,4)))}
  function restore(){try{var a=JSON.parse(sessionStorage.getItem("isp_compare")||"[]");selected=Array.isArray(a)?a.map(norm).filter(Boolean).slice(0,4):[]}catch(e){selected=[]}}
  async function json(path){var r=await fetch(path+"?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error(path+" HTTP "+r.status);return r.json()}
  function rows(x){if(Array.isArray(x))return x;if(x&&Array.isArray(x.stocks))return x.stocks;if(x&&Array.isArray(x.analyses))return x.analyses;if(x&&Array.isArray(x.results))return x.results;if(x&&x.data&&typeof x.data==='object')return Object.keys(x.data).map(function(k){var v=x.data[k]||{};if(!v.symbol)v.symbol=k;return v});return []}
  async function load(){if(ready)return;if(loading)return loading;loading=Promise.all([json("./data/nse_universe.json"),json("./data/search_analysis.json"),json("./data/live_quotes.json"),json("./data/fundamentals.json")]).then(function(a){var u=a[0],r=a[1],q=a[2],f=a[3];data.universe=Array.isArray(u)?u:(u&&Array.isArray(u.stocks)?u.stocks:[]);data.research={};rows(r).forEach(function(x){if(x&&x.symbol)data.research[norm(x.symbol)]=x});(window.integrated||[]).forEach(function(x){if(x&&x.symbol)data.research[norm(x.symbol)]=x});data.quotes=(q&&q.quotes)||{};data.fund={};var fs=Array.isArray(f)?f:(f&&Array.isArray(f.stocks)?f.stocks:[]);if(Array.isArray(f))fs.forEach(function(x){if(x&&x.symbol)data.fund[norm(x.symbol)]=x});else if(f&&f.stocks&&typeof f.stocks==='object')data.fund=f.stocks;ready=true}).finally(function(){loading=null});return loading}
  function list(){var out=[],seen={};data.universe.forEach(function(x){var s=norm(x.symbol);if(!s||seen[s])return;seen[s]=1;out.push({symbol:s,name:x.companyName||x.company||s})});Object.keys(data.research).forEach(function(s){if(!seen[s]){seen[s]=1;out.push({symbol:s,name:data.research[s].company||data.research[s].companyName||s})}});return out.sort(function(a,b){return a.symbol.localeCompare(b.symbol)})}
  function find(sym){return data.research[norm(sym)]||null}function quote(sym){return data.quotes[norm(sym)]||null}function fund(sym){return data.fund[norm(sym)]||null}
  function company(sym){var r=find(sym),u=data.universe.find(function(x){return norm(x.symbol)===norm(sym)}),f=fund(sym);return r&&(r.company||r.companyName)||u&&(u.companyName||u.company)||f&&(f.companyName||f.company)||sym}
  function css(){if(document.getElementById("isp-standalone-compare-css"))return;var s=document.createElement("style");s.id="isp-standalone-compare-css";s.textContent=".isp-compare-panel{margin-top:14px;border:1px solid #dfe5ee;border-radius:14px;background:#fff;padding:16px;box-shadow:0 4px 18px rgba(0,0,0,.06)}.isp-c-head{display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.isp-c-title{font-size:18px;font-weight:900}.isp-c-sub{font-size:11px;color:#667085;margin-top:4px}.isp-c-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px;margin-top:14px}.isp-c-input{position:relative}.isp-c-input input{width:100%;padding:10px;border:1px solid #ccd3df;border-radius:9px;font-size:13px;box-sizing:border-box}.isp-c-results{position:absolute;left:0;right:0;top:43px;z-index:999;background:#fff;border:1px solid #ccd3df;border-radius:9px;box-shadow:0 8px 22px rgba(0,0,0,.14);max-height:220px;overflow:auto;display:none}.isp-c-results.open{display:block}.isp-c-option{padding:9px 10px;border-bottom:1px solid #eef1f5;cursor:pointer;font-size:12px}.isp-c-option:hover{background:#f5f7fa}.isp-c-option span{color:#667085}.isp-c-actions{display:flex;gap:7px;flex-wrap:wrap;margin-top:12px}.isp-c-btn{border:1px solid #ccd3df;background:#fff;color:#172033;border-radius:9px;padding:8px 11px;font-weight:800;font-size:12px;cursor:pointer}.isp-c-btn.primary{background:#10182b;color:#fff}.isp-c-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px;margin-top:14px}.isp-c-card{border:1px solid #e1e6ef;border-radius:12px;padding:12px;background:#fff}.isp-c-symbol{font-size:16px;font-weight:900}.isp-c-name{font-size:11px;color:#667085;min-height:28px;margin-top:3px}.isp-c-live{font-size:18px;font-weight:900;margin:8px 0 2px}.isp-c-live.up{color:#16743b}.isp-c-live.down{color:#b42318}.isp-c-live-meta{font-size:10px;color:#667085;line-height:1.35}.isp-c-row{display:flex;justify-content:space-between;border-top:1px solid #eef1f5;margin-top:7px;padding-top:7px;font-size:11px}.isp-c-label{color:#667085}.isp-c-value{font-weight:900}.isp-c-msg{margin-top:12px;padding:10px;border-radius:9px;background:#f7f9fc;color:#667085;font-size:12px}.isp-c-status{margin-top:10px;font-size:11px;color:#667085}@media(max-width:850px){.isp-c-cards{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:600px){.isp-c-grid,.isp-c-cards{grid-template-columns:1fr}}";document.head.appendChild(s)}
  function host(){var input=document.getElementById("search");return input&&input.closest("section.panel")}
  function panel(){var h=host();if(!h)return null;var p=document.getElementById("isp-standalone-compare");if(!p){p=document.createElement("div");p.id="isp-standalone-compare";p.className="isp-compare-panel";h.appendChild(p)}return p}
  async function proxyJSON(url){var last=null;for(var i=0;i<PROXIES.length;i++){var ctl=new AbortController(),timer=setTimeout(function(){ctl.abort()},7000);try{var r=await fetch(PROXIES[i]+encodeURIComponent(url),{cache:"no-store",signal:ctl.signal});clearTimeout(timer);if(!r.ok)throw Error("proxy HTTP "+r.status);return await r.json()}catch(e){clearTimeout(timer);last=e}}throw last||Error("proxy unavailable")}
  async function fetchYahoo(sym){var u="https://query1.finance.yahoo.com/v8/finance/chart/"+encodeURIComponent(sym+".NS")+"?range=1d&interval=1m&includePrePost=false";var b=await proxyJSON(u),r=b&&b.chart&&b.chart.result&&b.chart.result[0];if(!r)throw Error("Yahoo quote unavailable");var m=r.meta||{},price=num(m.regularMarketPrice),prev=num(m.previousClose||m.chartPreviousClose);if(price==null){var c=((((r.indicators||{}).quote||[{}])[0]).close||[]).filter(function(x){return x!=null});price=num(c[c.length-1])}if(price==null)throw Error("Yahoo price missing");var ts=m.regularMarketTime?new Date(m.regularMarketTime*1000).toISOString():new Date().toISOString();return{price:price,previousClose:prev,change:prev!=null?price-prev:null,changePct:prev?((price-prev)/prev*100):null,timestamp:ts,source:"Yahoo Finance"}}
  async function fetchNse(sym){var u="https://www.nseindia.com/api/quote-equity?symbol="+encodeURIComponent(sym);var b=await proxyJSON(u),p=b&&b.priceInfo||{};if(p.lastPrice==null)throw Error("NSE LTP unavailable");return{price:num(p.lastPrice),previousClose:num(p.previousClose),change:num(p.change),changePct:num(p.pChange),timestamp:new Date().toISOString(),source:"NSE India"}}
  async function fetchLive(sym){try{return await fetchNse(sym)}catch(e){try{return await fetchYahoo(sym)}catch(y){var old=quote(sym);if(old)return Object.assign({},old,{source:"Published feed fallback"});return null}}}
  function liveHtml(sym){var q=live[sym]||quote(sym);if(!q)return '<div class="isp-c-live-meta">Live price: unavailable</div>';var p=num(q.price),pct=num(q.changePct),cl=pct==null?"":pct>0?"up":pct<0?"down":"";var when=q.timestamp?new Date(q.timestamp):null;var stamp=when&&!isNaN(when)?new Intl.DateTimeFormat("en-IN",{dateStyle:"short",timeStyle:"short",timeZone:"Asia/Kolkata"}).format(when)+" IST":"";return '<div class="isp-c-live '+cl+'">'+esc(money(p))+'</div><div class="isp-c-live-meta"><b>'+(q.source||"Market quote")+'</b>'+((pct!=null)?' · '+(pct>0?'+':'')+pct.toFixed(2)+'%':'')+(stamp?' · '+esc(stamp):'')+'</div>'}
  function card(sym){var r=find(sym)||{},q=quote(sym)||r.liveQuote||{},f=fund(sym)||{},qm=r.quantitative||{},qs=qm.score??r.quantitativeScore??r.score,conf=qm.confidence??r.confidence,signal=qm.signal??r.signal,risk=qm.risk??r.risk,fs=f.score??f.healthScore,health=f.health??f.status;return '<article class="isp-c-card"><div class="isp-c-symbol">'+esc(sym)+'</div><div class="isp-c-name">'+esc(company(sym))+'</div><div data-live="'+esc(sym)+'">'+liveHtml(sym)+'</div><div class="isp-c-row"><span class="isp-c-label">Integrated</span><span class="isp-c-value">'+score(r.integratedScore)+'</span></div><div class="isp-c-row"><span class="isp-c-label">Quantitative</span><span class="isp-c-value">'+score(qs)+'</span></div><div class="isp-c-row"><span class="isp-c-label">Confidence</span><span class="isp-c-value">'+score(conf)+'</span></div><div class="isp-c-row"><span class="isp-c-label">Signal</span><span class="isp-c-value">'+esc(signal||'—')+'</span></div><div class="isp-c-row"><span class="isp-c-label">Risk</span><span class="isp-c-value">'+esc(risk||'—')+'</span></div><div class="isp-c-row"><span class="isp-c-label">Fundamental</span><span class="isp-c-value">'+score(fs)+'</span></div><div class="isp-c-row"><span class="isp-c-label">Health</span><span class="isp-c-value">'+esc(health||'—')+'</span></div></article>'}
  async function refreshLive(p){var syms=selected.filter(Boolean),status=p.querySelector('#ispCstatus'),out=p.querySelector('#ispCoutput');if(status)status.textContent="Getting latest market prices…";await Promise.all(syms.map(async function(sym){live[sym]=await fetchLive(sym)}));if(out&&syms.length>=2)out.innerHTML='<div class="isp-c-cards">'+syms.map(card).join('')+'</div>';if(status)status.textContent="Prices checked using NSE India first, Yahoo Finance second; stored feed used only as fallback."}
  function render(p){var all=list();p.innerHTML='<div class="isp-c-head"><div><div class="isp-c-title">⚖ Compare Stocks</div><div class="isp-c-sub">Select 2–4 NSE stocks for side-by-side research with market prices.</div></div><button type="button" class="isp-c-btn" id="ispCclose">Close</button></div><div class="isp-c-grid">'+[0,1,2,3].map(function(i){return '<div class="isp-c-input"><input autocomplete="off" data-ci="'+i+'" placeholder="Stock '+(i+1)+(i<2?' — required':' — optional')+'" value="'+esc(selected[i]||'')+'"><div class="isp-c-results" data-cr="'+i+'"></div></div>'}).join('')+'</div><div class="isp-c-actions"><button type="button" class="isp-c-btn primary" id="ispCcompare">Compare selected</button><button type="button" class="isp-c-btn" id="ispCrefresh">↻ Refresh live prices</button><button type="button" class="isp-c-btn" id="ispCclear">Clear</button></div><div id="ispCstatus" class="isp-c-status">Prices will be checked when you compare.</div><div id="ispCoutput"></div>';function closeLists(){p.querySelectorAll('.isp-c-results').forEach(function(x){x.classList.remove('open')})}function choose(i,s){selected[i]=norm(s);save();render(p)}p.querySelectorAll('[data-ci]').forEach(function(inp){var i=Number(inp.dataset.ci);function update(){var box=p.querySelector('[data-cr="'+i+'"]'),q=norm(inp.value),matches=all.filter(function(x){return(!q||norm(x.symbol).indexOf(q)>=0||norm(x.name).indexOf(q)>=0)&&(!selected.includes(x.symbol)||selected[i]===x.symbol)}).slice(0,25);box.innerHTML=matches.map(function(x){return '<div class="isp-c-option" data-s="'+esc(x.symbol)+'"><b>'+esc(x.symbol)+'</b> <span>'+esc(x.name)+'</span></div>'}).join('')||'<div class="isp-c-option">No NSE stock found.</div>';box.classList.add('open');box.querySelectorAll('[data-s]').forEach(function(el){el.onclick=function(){choose(i,el.dataset.s)}})}inp.onfocus=update;inp.oninput=update;inp.onkeydown=function(e){if(e.key==='Enter'){var x=p.querySelector('[data-cr="'+i+'"] .isp-c-option[data-s]');if(x){e.preventDefault();x.click()}}if(e.key==='Escape')closeLists()}});p.querySelector('#ispCclose').onclick=function(){p.remove()};p.querySelector('#ispCclear').onclick=function(){selected=[];save();render(p)};p.querySelector('#ispCcompare').onclick=function(){var a=selected.filter(Boolean),out=p.querySelector('#ispCoutput');if(a.length<2){out.innerHTML='<div class="isp-c-msg">Please select at least 2 stocks.</div>';return}out.innerHTML='<div class="isp-c-cards">'+a.map(card).join('')+'</div>';refreshLive(p)};p.querySelector('#ispCrefresh').onclick=function(){if(selected.filter(Boolean).length>=2)refreshLive(p);else p.querySelector('#ispCstatus').textContent="Select at least 2 stocks first."}}
  function open(){css();restore();var p=panel();if(!p)return;p.innerHTML='<div class="isp-c-msg">Loading Compare…</div>';p.scrollIntoView({behavior:"smooth",block:"start"});load().then(function(){render(p)}).catch(function(e){p.innerHTML='<div class="isp-c-msg"><b>Compare could not load.</b><br>'+esc(e.message||e)+'</div>'})}
  window.__ispTrialCompareOpen=open;document.addEventListener('click',function(e){var b=e.target.closest&&e.target.closest('#ispCompareBtn');if(b){e.preventDefault();e.stopPropagation();open()}},true);window.addEventListener('isp:open-trial-compare',open);
  function ensureButton(){var h=host();if(!h||document.getElementById('ispCompareBtn'))return;var bar=document.createElement('div');bar.style.cssText='display:flex;gap:8px;margin-top:10px;flex-wrap:wrap';bar.innerHTML='<button type="button" id="ispCompareBtn" class="isp-c-btn">⚖ Compare</button>';h.appendChild(bar)}
  function start(){css();ensureButton();var ob=new MutationObserver(ensureButton);ob.observe(document.body,{childList:true,subtree:true});setTimeout(function(){ob.disconnect()},120000)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
