/* Indian Stock Pro — live IPO + dividend calendar sections */
(function(){
  "use strict";
  const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
  const fmtDate=v=>{if(!v)return "—";const d=new Date(v+"T00:00:00+05:30");return Number.isNaN(d.getTime())?esc(v):new Intl.DateTimeFormat("en-IN",{day:"2-digit",month:"short",year:"numeric",timeZone:"Asia/Kolkata"}).format(d)};
  const nowIST=()=>new Date(new Date().toLocaleString("en-US",{timeZone:"Asia/Kolkata"}));
  function styles(){if(document.getElementById("isp-events-style"))return;const s=document.createElement("style");s.id="isp-events-style";s.textContent=`
  .isp-events{margin-bottom:18px}.isp-events-head{display:flex;justify-content:space-between;align-items:flex-start;gap:15px;flex-wrap:wrap}.isp-events-head p{margin:6px 0 0;color:#667085;font-size:13px}.isp-events-updated{font-size:11px;color:#667085;background:#f5f7fa;border:1px solid #e1e6ef;padding:7px 10px;border-radius:999px}.isp-event-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.isp-event-card{border:1px solid #e1e6ef;border-radius:14px;padding:14px;background:#fff}.isp-event-top{display:flex;justify-content:space-between;gap:10px}.isp-event-name{font-size:16px;font-weight:900}.isp-event-symbol{font-size:12px;color:#667085;margin-top:3px}.isp-event-badge{font-size:10px;font-weight:900;padding:5px 8px;border-radius:999px;background:#eaf7ee;color:#16743b;height:max-content}.isp-event-badge.open{background:#fff4d8;color:#8a5a00}.isp-event-badge.closed{background:#f1f3f5;color:#596273}.isp-event-row{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:11px}.isp-event-cell{background:#f7f9fc;border-radius:9px;padding:9px}.isp-event-label{font-size:10px;color:#667085;text-transform:uppercase;font-weight:800}.isp-event-value{font-size:13px;font-weight:800;margin-top:3px}.isp-event-source{margin-top:10px;font-size:10px;color:#667085}.isp-event-source a{color:#2457a6;font-weight:800;text-decoration:none}.isp-event-empty{color:#667085;padding:12px 0}.isp-events-note{margin-top:10px;font-size:11px;color:#667085;line-height:1.45}.isp-event-divider{height:1px;background:#eef1f5;margin:18px 0}.isp-red-notice{border:1px solid #d92d20;background:#fff1f0;color:#b42318;border-radius:12px;padding:11px 13px;font-size:12px;line-height:1.45;margin-bottom:12px}.isp-red-notice b{color:#a20f0a}@media(max-width:700px){.isp-event-grid{grid-template-columns:1fr}.isp-event-row{grid-template-columns:1fr 1fr}}
  `;document.head.appendChild(s)}
  function card(x,type){if(type==='ipo')return `<article class="isp-event-card"><div class="isp-event-top"><div><div class="isp-event-name">${esc(x.company)}</div><div class="isp-event-symbol">${esc(x.symbol)} · ${esc(x.segment)}</div></div><span class="isp-event-badge ${x.status==='CLOSED'?'closed':x.status==='OPEN'?'open':''}">${esc(x.status||'UPCOMING')}</span></div><div class="isp-event-row"><div class="isp-event-cell"><div class="isp-event-label">IPO dates</div><div class="isp-event-value">${fmtDate(x.openDate)} – ${fmtDate(x.closeDate)}</div></div><div class="isp-event-cell"><div class="isp-event-label">Listing</div><div class="isp-event-value">${fmtDate(x.listingDate)}</div></div><div class="isp-event-cell"><div class="isp-event-label">Price band</div><div class="isp-event-value">${esc(x.priceBand||'—')}</div></div><div class="isp-event-cell"><div class="isp-event-label">Issue size</div><div class="isp-event-value">${esc(x.issueSize||'—')}</div></div></div><div class="isp-event-source">Source: ${esc(x.source)} · <a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">verify latest</a></div></article>`;
  return `<article class="isp-event-card"><div class="isp-event-top"><div><div class="isp-event-name">${esc(x.company)}</div><div class="isp-event-symbol">${esc(x.symbol)}</div></div><span class="isp-event-badge ${x.status==='RECENT'?'closed':''}">${esc(x.status||'UPCOMING')}</span></div><div class="isp-event-row"><div class="isp-event-cell"><div class="isp-event-label">Dividend</div><div class="isp-event-value">${esc(x.dividend||'—')}</div></div><div class="isp-event-cell"><div class="isp-event-label">Ex-date</div><div class="isp-event-value">${fmtDate(x.exDate)}</div></div><div class="isp-event-cell"><div class="isp-event-label">Record date</div><div class="isp-event-value">${fmtDate(x.recordDate)}</div></div><div class="isp-event-cell"><div class="isp-event-label">Type</div><div class="isp-event-value">${esc(x.type||'Dividend')}</div></div></div><div class="isp-event-source">Source: ${esc(x.source)} · <a href="${esc(x.sourceUrl)}" target="_blank" rel="noopener">verify latest</a></div></article>`;
  }
  async function load(path){const r=await fetch(path+"?v="+Date.now(),{cache:"no-store"});if(!r.ok)throw Error("HTTP "+r.status);return r.json()}
  function makePanel(id,title,desc,data,type){const p=document.createElement("section");p.className="panel isp-events";p.id=id;const items=(data.items||[]);p.innerHTML=`<div class="isp-events-head"><div><h2>${type==='ipo'?'🧾 IPO Calendar':'💰 Dividend Calendar'}</h2><p>${esc(desc)}</p></div><span class="isp-events-updated">Updated ${esc(data.updatedAt||data.snapshotDate||'—')}</span></div><div class="isp-red-notice"><b>Important:</b> This is an information calendar, not an investment recommendation. Dates, amounts, price bands and status can change. Always verify the latest exchange or issuer filing before acting.</div><div class="isp-event-grid">${items.length?items.map(x=>card(x,type)).join(''):'<div class="isp-event-empty">No current entries available.</div>'}</div><div class="isp-events-note">${esc(data.note||'Latest available published data is shown. If a source has not published a current event, the app does not invent one.')}</div>`;return p}
  async function render(){styles();try{const [ipo,div]=await Promise.all([load('./data/ipo_calendar.json'),load('./data/dividend_calendar.json')]);const anchor=document.getElementById('summary')?.closest('section.panel');if(!anchor)return;document.getElementById('ispIPOCalendar')?.remove();document.getElementById('ispDividendCalendar')?.remove();const ipoPanel=makePanel('ispIPOCalendar','IPO Calendar','Upcoming, open and recently closed public issues with key dates and price bands.',ipo,'ipo');const divPanel=makePanel('ispDividendCalendar','Dividend Calendar','Upcoming dividend-related dates and recently completed dividend events.',div,'dividend');anchor.parentNode.insertBefore(ipoPanel,anchor);anchor.parentNode.insertBefore(divPanel,anchor); }catch(e){console.warn('IPO/dividend calendars unavailable',e)}}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',render);else render();
})();

/* Trial-only loader: keep compare UI isolated from main. */
(function(){
  "use strict";
  if(!/github\.io\/IndianStockPro_v1\.2/i.test(location.hostname+location.pathname))return;
  if(location.pathname.indexOf("/IndianStockPro_v1.2/")===-1)return;
  if(window.__ispCompareUiLoader)return;
  window.__ispCompareUiLoader=true;
  var s=document.createElement("script");
  s.src="./compare-ui.js?v=20260820";
  s.onload=function(){console.log("Indian Stock Pro trial compare UI loaded")};
  s.onerror=function(){console.warn("Trial compare UI could not be loaded")};
  document.head.appendChild(s);
})();
