/* Indian Stock Pro — Fundamentals layer */
(function(){
  "use strict";
  const FEED="./data/fundamentals.json?ts="+Date.now();
  const esc=v=>String(v??"").replace(/[&<>\"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'\"':"&quot;","'":"&#39;"}[m]));
  const fmt=(v,s="")=>v==null||Number.isNaN(Number(v))?"—":Number(v).toLocaleString("en-IN",{maximumFractionDigits:2})+s;
  const labels={revenueGrowth:["Revenue growth","%"],earningsGrowth:["Earnings growth","%"],roe:["ROE","%"],debtToEquity:["Debt / equity",""],pe:["P/E",""],dividendYield:["Dividend yield","%"]};
  function css(){if(document.getElementById("isp-fund-css"))return;const s=document.createElement("style");s.id="isp-fund-css";s.textContent=`.isp-fund{margin-bottom:18px}.isp-fund-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.isp-fund-note{font-size:12px;color:#667085;line-height:1.45}.isp-fund-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.isp-fund-card{border:1px solid #e1e6ef;border-radius:13px;padding:14px;background:#fff}.isp-fund-top{display:flex;justify-content:space-between;gap:10px}.isp-fund-symbol{font-weight:900;font-size:16px}.isp-fund-company{font-size:12px;color:#667085;margin-top:3px}.isp-fund-score{font-size:18px;font-weight:900}.isp-fund-health{display:inline-block;margin-top:9px;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:900}.isp-fund-health.strong,.isp-fund-health.good{background:#eaf7ee;color:#16743b}.isp-fund-health.neutral{background:#fff4d8;color:#8a5a00}.isp-fund-health.weak{background:#fdecec;color:#b42318}.isp-fund-health.limited,.isp-fund-health.data-unavailable{background:#f1f3f5;color:#596273}.isp-fund-metrics{display:grid;grid-template-columns:repeat(2,1fr);gap:7px;margin-top:10px}.isp-fund-metric{background:#f5f7fa;border-radius:8px;padding:8px}.isp-fund-metric small{display:block;color:#667085;font-size:10px}.isp-fund-metric b{display:block;margin-top:2px;font-size:12px}.isp-fund-foot{font-size:10px;color:#7a8494;margin-top:10px}.isp-fund-refresh{border:1px solid #ccd3df;background:#fff;color:#172033;padding:8px 12px;border-radius:9px;font-weight:800;cursor:pointer}.isp-fund-refresh:disabled{opacity:.55;cursor:wait}@media(max-width:800px){.isp-fund-grid{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function mount(data){css();let root=document.getElementById("isp-fundamentals");if(!root){root=document.createElement("section");root.id="isp-fundamentals";root.className="panel isp-fund";const cards=document.getElementById("integratedCards")?.closest(".panel");const summary=document.querySelector(".summary")?.closest(".panel");if(cards?.parentNode)cards.parentNode.insertBefore(root,cards.nextElementSibling);else if(summary?.parentNode)summary.parentNode.appendChild(root);else document.querySelector(".container")?.appendChild(root)}const items=Object.values(data?.stocks||{}).filter(Boolean).slice(0,30);root.innerHTML=`<div class="isp-fund-head"><div><h2>📊 Fundamental Health</h2><div class="isp-fund-note">Revenue, earnings, profitability, leverage and valuation metrics for the current analysis universe. This is an informational layer and does not replace independent research.</div></div><button class="isp-fund-refresh" type="button">↻ Refresh fundamentals</button></div><div class="isp-fund-grid">${items.map(x=>{const cls=(x.health||"").toLowerCase().replace(/[^a-z]+/g,"-");const keys=Object.keys(labels);return `<article class="isp-fund-card"><div class="isp-fund-top"><div><div class="isp-fund-symbol">${esc(x.symbol)}</div><div class="isp-fund-company">${esc(x.companyName)}</div></div><div class="isp-fund-score">${x.score==null?"—":esc(x.score)+"/100"}</div></div><span class="isp-fund-health ${cls}">${esc(x.health||"Data unavailable")}</span><div class="isp-fund-metrics">${keys.map(k=>{const [label,suf]=labels[k];return `<div class="isp-fund-metric"><small>${label}</small><b>${fmt(x.metrics?.[k],suf)}</b></div>`}).join("")}</div><div class="isp-fund-foot">Snapshot: ${esc(x.snapshotAt||data.generatedAt||"unknown")}</div></article>`}).join("")}</div>`;root.querySelector("button")?.addEventListener("click",()=>load(true))}
  async function load(manual){const old=document.getElementById("isp-fundamentals");const btn=old?.querySelector("button");if(btn){btn.disabled=true;btn.textContent="↻ Loading…"}try{const r=await fetch(FEED+(manual?"&manual=1":""),{cache:"no-store"});if(!r.ok)throw Error(r.status);mount(await r.json())}catch(e){if(old)old.innerHTML=`<h2>📊 Fundamental Health</h2><div class="error">Fundamental snapshot is temporarily unavailable. Existing quantitative, price and market-intelligence layers are unchanged.</div>`}finally{const b=document.querySelector("#isp-fundamentals button");if(b){b.disabled=false;b.textContent="↻ Refresh fundamentals"}}}
  if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",()=>load(false));else load(false);
})();
