plugins {
    id 'com.android.application'
}

android {
    namespace 'com.shivsmile.indianstockpro'
    compileSdk 35
    defaultConfig {
        applicationId 'com.shivsmile.indianstockpro'
        minSdk 23
        targetSdk 35
        versionCode 19
        versionName '1.9'
    }
    buildTypes {
        release {
            minifyEnabled false
            shrinkResources false
        }
    }
}
